// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpdcayvcbizanlmepapa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwZGNheXZjYml6YW5sbWVwYXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzQ5MTksImV4cCI6MjA3Mzg1MDkxOX0.p3hvc8AWUBHMo7VamyRoYfgibDivy2lWvlvsggtkoJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});